# sudo: required
language: go
go:
  - 1.12
# env:
#   - GO111MODULE=on

os:
  - linux
# branches:
#   only:
#     - master
#     - develop
#     - /^v\d+\.\d+\.\d+(\.\d+)?(-\S*)?$/
      
services:
  - docker
  - redis-server

script:
  - go get -u github.com/project-flogo/cli/...
  - env GO111MODULE=on go test -p 1 ./...

notifications:
  email:
    on_failure: always
    on_success: always
    recipients:
      - rpolishe@tibco.com
      - lmekala@tibco.com
      - nthota@tibco.com
      - ykalidin@tibco.com
      - asnodgra@tibco.com  
